version: '3'

services:
  web:
    build: ./web
    ports:
      - "5000:5000"

  database:
    image: 'mongo'
    container_name: 'mongo-container'
    environment:
      - MONGO_INITDB_DATABASE=flask_db
      - MONGO_INITDB_ROOT_USERNAME=dev
      - MONGO_INITDB_ROOT_PASSWORD=dev
    ports:
      - '27017-27019:27017-27019'